In [1]:
import numpy as np

# **Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [8]:
N = 10
print(np.arange(N-1, -1, -1))

[9 8 7 6 5 4 3 2 1 0]


# **Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [10]:
N = 5                                           #определяет также размерность матрицы
matrix =  np.diag(np.arange(N, -1, -1), k=0)    #генерация диагональной матрицы
matrix_trace = sum(np.diagonal(matrix))         #след матрицы
print(matrix)
print(matrix_trace)

[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
15


# **Задание 3**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3


In [13]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )  #матрица левой части
b = np.array( [4, 12, -3] )                          #вектор столбец правой части
from numpy import linalg                             #импортирование библиотеки по решению линейных уравнений (транспонирование, умножение)
solve = linalg.solve(a, b)                           #получение значений х, у, z
print(solve)

[ 0.46666667  3.84444444 -5.55555556]


# Задача 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [14]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [15]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [19]:
def cosine( a, b ):                                            #вычисление косинусного расстояния, функция из лекционной части
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )  
    return np.dot( a, b ) / ( aLength * bLength )
cosine_list = []                                                    #cоздаем пустой список с косинусами

for user in users_stats:                                            #создаем цикл по исходному списку
    cosine_list.append(cosine(next_user_stats, user))               #вычисляем косинусное расстояние между текущим элементом цикла и новым пользователем
                                                                    #формируем список через append
max_cosine_list = users_stats[cosine_list.index(max(cosine_list))]  #ищем максимальное значение в списке

print(f'Поведение нового пользователя схоже с пользователем {max_cosine_list}')

Поведение нового пользователя схоже с пользователем [0 1 1 0 0 0]
